trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Installing .NET Core SDK...'
  inputs:
    version: 3.0.100-preview6-012264

- task: NuGetToolInstaller@0
  displayName: 'Installing Nuget Tools...'
  inputs:
    versionSpec: '4.9.2'

- script: dotnet build --configuration $(buildConfiguration) src/Blazored.Modal/Blazored.Modal.csproj
  displayName: 'Building $(buildConfiguration)...'

- task: DotNetCoreCLI@2
  displayName: 'Generating Nuget Package... '
  inputs:
    command: pack
    arguments: --no-build
    packagesToPack: src/Blazored.Modal/Blazored.Modal.csproj
    configuration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
